import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const lang = navigator.appName === 'Netscape' ? navigator.language : navigator.userLanguage;
let config = {};
window.setLang = (_lang) => {
      switch (_lang) {
          case 'zh-CN':
          case 'zh-SG':
              config = {
                  name: '搜索酱',
                  lang: '语言',
                  setLang: '设置语言',
                  outOfDate: '发现新版本，点击前往更新',
                  description: '详细描述',
                  moreOptions: '更多选项',
                  showIcon: '显示分组',
                  hideIcon: '隐藏分组',
                  rulesStore: '搜索引擎仓库',
                  import: '导入设置',
                  importFromClipboard: '从剪贴板导入',
                  exportTitle: '导出配置，单击导出搜索引擎配置，长按导出完整配置',
                  exportCache: '导出图标缓存',
                  general: '常规设置',
                  searchEngines: '搜索引擎',
                  exportConfig: '导出设置',
                  presetGroupName: '预置分组名',
                  presetGroupValue: '预置分组内容',
                  addGroup: '添加预置分组',
                  addGroupTips: '添加一组预置高亮词，以在不同场景重复调用',
                  findInPage: '页内查找',
                  customSearch: '划词搜索',
                  about: '关于',
                  showInSearchEngine: '高亮搜索引擎页面',
                  showInSearchEngineTips: '在搜索引擎结果页高亮关键词',
                  showInSearchJumpPage: '高亮搜索引擎页面打开的站点',
                  showInSearchJumpPageTips: '在搜索引擎页面点击打开的站点内高亮关键词',
                  currentTypeFirst: '置顶当前分组',
                  currentTypeFirstTips: '开启后，当前分组将前移至第一位',
                  mouseLeaveToHide: '鼠标移开时自动隐藏',
                  mouseLeaveToHideTips: '当鼠标从搜索条或者搜索磁贴上移开时自动隐藏搜索酱',
                  limitInPageLen: '限制关键词最小长度',
                  limitInPageLenTips: '不对长度小于此值的关键词进行高亮',
                  ignoreWords: '忽略关键词列表',
                  inPageWordsStyles: '关键词样式',
                  inPageWordsAddStyles: '自定义关键词CSS，数组内按顺序指向对应关键词',
                  defaultPicker: '自动开启元素选择',
                  defaultPickerTips: '打开搜索输入框时自动开启元素选择',
                  emptyAfterCloseInput: '关闭时清空高亮',
                  emptyAfterCloseInputTips: '关闭搜索输入框时清空高亮关键词',
                  altToHighlight: 'Alt 划选立即高亮',
                  altToHighlightTips: '使用搜索输入框的页内搜索功能时，使用 Alt 划选后立即高亮',
                  disableInputOnWords: '划选文字时不弹出搜索输入框',
                  disableInputOnWordsTips: '正在划选文字时使用快捷键不弹出搜索输入框，仅显示搜索条',
                  inPageRule: '站点自动高亮规则',
                  errorNoType: '请输入分组名',
                  errorSameType: '分组名不能重复',
                  editType: '编辑分组',
                  typeName: '分组名',
                  typeIcon: '分组图标',
                  category: '分组',
                  iconTips: '图标可使用 FontAwsome、图片链接或者 base64 代码',
                  typeMatch: '根据网址筛选当前分组，设为 0 隐藏该分组',
                  typeEnableSelTxt: '对选择文字生效',
                  typeEnableSelImg: '对图片生效',
                  typeEnableSelAudio: '对音频生效',
                  typeEnableSelVideo: '对视频生效',
                  typeEnableSelLink: '对链接生效',
                  typeEnableSelPage: '对页面生效',
                  typeOpenInNewTab: '启用后该组链接将默认在新窗口打开',
                  openSelect: '打开选项',
                  openInNewTabOption: '新标签页打开',
                  openInCurrentOption: '当前页打开',
                  openInDefaultOption: '默认',
                  showCurrent: '显示当前站点',
                  showCurrentTips: '匹配到当前站点时，不隐藏当前站点图标',
                  delete: '删除',
                  deleteOk: '删除完毕',
                  cancel: '取消',
                  edit: '编辑',
                  add: '新增',
                  editSite: '编辑站点',
                  addSite: '新增站点',
                  addType: '新增分组',
                  siteName: '站点名',
                  siteUrl: '站点 URL',
                  siteIcon: '站点图标',
                  siteKeywords: '搜索词提取',
                  keywordRegTips: '单个关键词：wd；多个：wd|qw|key；正则分组：(?:wd|w)/(.*?)\\b；选择器：input#su',
                  kwFilter: '搜索词或者指向链接的筛选正则',
                  kwFilterTips: '当对象文字或者链接不匹配正则时隐藏该引擎',
                  siteMatch: '根据页面网址的正则匹配当前引擎，设为 0 强制隐藏该站',
                  siteCharset: '站点编码',
                  toolbarPosition: '工具栏位置',
                  portrait: '纵向',
                  horizontal: '横向',
                  openInNewTab: '默认在新标签页打开链接',
                  openInNewTabTips: '启用后链接将全部默认在新标签页打开',
                  enableInPage: '启用划词搜索',
                  enableInPageTips: '启用后选择文字并长按鼠标右键可调出工具长条',
                  bindFunctionKey: '按住此功能键单击鼠标右键可立即唤出当前分组的磁贴',
                  ctrlKey: 'Ctrl键',
                  altKey: 'Alt键',
                  shiftKey: 'Shift键',
                  metaKey: 'meta键',
                  configContent: '设置源码',
                  batchOpenConfirm: '批量搜索确认框',
                  batchOpenConfirmDefault: '默认',
                  batchOpenConfirmAlways: '总是需要确认',
                  batchOpenConfirmNo: '不需要确认',
                  copy: '复制',
                  save: '保存',
                  autoClose: '自动合上分组',
                  autoDelay: '隐藏延时',
                  needName: '需要名称',
                  needUrl: '需要 URL',
                  wrongImg: '非有效图标地址',
                  overOpen: '鼠标划过时分组自动展开',
                  overOpenTips: '选中此项则当鼠标划过分组图标，对应分组将自动展开',
                  selectToShow: '划选立即调用磁贴',
                  selectToShowTips: '启用后划选立即调出磁贴',
                  autoCloseTips: '启用之后一旦鼠标离开搜索条，已打开的分组抽屉将会自动合上',
                  enableShortcut: '启用站点快捷键',
                  enableShortcutTips: '启用后，将使得所有为站点分配的快捷键生效',
                  shortcut: '快捷键',
                  siteShotcut: '搜索快捷键',
                  switchSitesKey: '当前分组内引擎切换快捷键，仅当匹配到当前引擎时有效',
                  switchSitesPreKey: '向前切换快捷键',
                  switchSitesNextKey: '向后切换快捷键',
                  initShow: '默认拉出工具栏',
                  initShowTips: '打开页面立即拉出工具栏，鼠标划过后再贴边隐藏',
                  configPage: '默认设置页',
                  configPageTips: '将当前页面设为默认设置页',
                  alwaysShow: '总是显示工具栏',
                  alwaysShowTips: '即使没有匹配到搜索引擎也显示工具栏',
                  presetCss: '预置样式',
                  presetCssTips: '选择后载入预置样式',
                  customCss: '自定义样式',
                  replaceCss: '确定要替换当前编辑的样式吗？',
                  enableInInput: '监听输入框',
                  enableInInputTips: '启用后，在输入框内生效',
                  fontAwesomeCss: 'FontAwesome CDN地址',
                  nobatch: '不参与批量打开',
                  hideNotMatch: '非当前引擎则隐藏该项',
                  typeMatchTips: '仅在匹配站点显示该分组',
                  siteUrlTips: '%s 查询词; %t 目标链接; %u 页面地址; %h 页面域名',
                  customSize: '缩放工具栏',
                  tilesZoom: '缩放磁贴',
                  tipsZoom: '缩放提示文本',
                  zoomDrag: '缩放拖拽圆盘',
                  typeOpenTime: '分组展开耗时',
                  longPressTime: '长按时间',
                  typeShotcut: '批量打开快捷键',
                  enableRightMouse: '启用鼠标右键长按',
                  enableRightMouseTips: '启用后，在目标对象上长按鼠标右键可唤出搜索条',
                  enableLeftMouse: '启用鼠标左键',
                  enableLeftMouseTips: '启用后，在目标对象上单击鼠标左键也能唤出搜索条',
                  enableMiddleMouse: '启用鼠标中键',
                  enableMiddleMouseTips: '启用后，在目标对象上单击鼠标中键也能唤出搜索条',
                  cacheSwitch: '缓存图标',
                  sameSiteName: '在【#t#】下存在同名站点',
                  sameShortcut: '【#t#】已经绑定了相同快捷键',
                  noIcons: '纯文本模式',
                  noIconsTips: '隐藏图标，仅显示纯文本',
                  showEngineWords: '显示引擎名',
                  showEngineWordsTips: '在引擎图标下方显示引擎名',
                  noAni: '禁止动画效果',
                  noAniTips: '禁止所有动画效果',
                  quickAddRule: '快速添加搜索引擎',
                  quickAddRuleTips: '按住 Ctrl + Alt 点击任意搜索框快速添加搜索引擎',
                  searchMycroft: '💎 在 mycroftproject 上搜索其他人编辑好的搜索引擎并一键导入，例如：“谷歌学术”',
                  showSiteLists: '显示引擎列表',
                  showSiteListsTips: '启用后将在分组图标旁启用引擎列表面板',
                  alwaysShowSiteLists: '总是显示引擎列表',
                  alwaysShowSiteListsTips: '启用后，分组抽屉打开时也会显示引擎列表',
                  disableTypeOpen: '禁用分组点击展开',
                  disableTypeOpenTips: '点击分组后不再展开，而是显示引擎列表',
                  historyLength: '历史站点数',
                  historyLengthTips: '在默认展开的分组末尾插入数个最近访问的站点',
                  historyInsertFirst: '将历史站点插入到分组开头',
                  historyInsertFirstTips: '将最近访问的站点插入到分组开头，否则插入到末尾',
                  shiftLastUsedType: '前移上次使用的分组',
                  shiftLastUsedTypeTips: '将上次使用的分组前移至当前分组之后',
                  sortType: '自动排序分组',
                  sortTypeTips: '自动按照访问次数重新排序分组',
                  sortSite: '自动排序引擎',
                  sortSiteTips: '自动按照访问次数重新排序分组内的引擎',
                  multiline: '多行搜索，选取多行文字时，以换行符分隔，按行搜索',
                  multilineLabel: '开关',
                  multilineGap: '搜索间隔',
                  disable: '禁用',
                  enable: '启用',
                  ask: '询问',
                  filterEngine: '筛选引擎',
                  verifyResult: '验证结果',
                  verifyBtn: '批量验证所有引擎可用性',
                  verifying: '验证中……',
                  verifyFinish: '验证完成',
                  batchAction: '批量操作',
                  selectAll: '全选',
                  invert: '反选',
                  deleteConfirm: '你确定要删除这些站点吗？',
                  moveTo: '移动至',
                  moveToConfirm: '你确定要将这些站点移动至【#t#】吗?',
                  autoHide: '自动隐藏搜索条',
                  autoHideTips: '达到上方设置延时之后，自动隐藏搜索条',
                  autoHideAll: '完全隐藏',
                  autoHideAllTips: '隐藏时使得搜索条完全消失',
                  unsetTips: '未设置',
                  resizePageTips: '不隐藏并且收缩页面',
                  minSizeMode: '极简模式',
                  minSizeModeTips: '开启后，搜索条将只显示当前分组，直至鼠标划过',
                  dragToSearch: '开启拖拽搜索',
                  dragToSearchTips: '开启后拖拽文字、链接或者图片进行搜索，内圈为当前分组(即首个划词/搜图/链接/页面分组)前 6 个站点，可自行前往搜索引擎标签页修改，外圈为最近使用的站点',
                  sameSiteUrl: '站点Url不能重复',
                  clone: '克隆',
                  cloneConfirm: '你确定要将这些站点克隆至 【#t#】?',
                  cloneAction: '你想要将它们克隆成一个集合吗?',
                  groupName: '集合名',
                  donate: '你好！我是 Hoothin，也是 SearchJumper 的作者。\n\n我很高兴能与大家分享 SearchJumper，这是一个完全开源免费的项目。虽然它的开发耗费了我大量的时间，但只要有人能从中获得帮助，一切都是值得的。\n\n如果您觉得 SearchJumper 对您有所帮助，并且愿意支持我的努力，我真心希望您考虑以下几种方式来夸夸我。您的支持将是我前进的动力，让我能够继续改进和提供更好的作品。\n\n- 捐赠：您可以考虑通过捐赠来支持 SearchJumper 的未来发展。即使是一小笔捐款，都将对我产生巨大的鼓舞和激励。\n- 反馈和分享：如果您有任何有关 SearchJumper 的反馈或建议，或者愿意与他人分享您的使用体验，那将是我最开心的事情。您的反馈将帮助我不断改进和优化 SearchJumper，让更多的人受益。\n- 社区参与：欢迎加入 SearchJumper 的 Discord 频道，与其他用户一起分享您的见解和经验。这是一个互相学习和支持的平台，您的参与将使社区更加繁荣。\n\n再次感谢您对 SearchJumper 的支持！我将竭尽全力优化改进这个项目。谢谢您的捐赠和夸奖，我由衷感激！💞',
                  importBookmarks: '导入浏览器书签',
                  sync: 'Webdav 同步',
                  host: '服务器地址',
                  username: '用户名',
                  password: '密码',
                  path: '路径',
                  syncTips: 'Webdav 服务器需要支持自设 cors（不支持坚果云等），自行添加 allowed_hosts: https://hoothin.github.io',
                  expandType: '展开分组',
                  expandTypeTips: '展开分组，不隐藏同一分组中超出数量的引擎',
                  expandTypeLength: '显示引擎数',
                  expandTypeLengthTips: '隐藏超出此数量的引擎',
                  jsonToolong: '站点数据过于庞大，是否继续格式化为JSON文本？',
                  imgTooBig: '图片大于50kb，是否继续上传？',
                  cacheSwitchTips: '在后台缓存图标为 base64 图片至配置，以免 icon 请求拉低性能。注意开始缓存时会弹出跨域请求，缓存过程可能卡顿，此时勿关闭配置页',
                  searchFontawesome: '🚩 搜索 FontAwesome 图标用于分组项',
                  localAppAddBtn: '添加自定义本地应用调用',
                  localApp: '本地应用调用',
                  localAppCall: '调用命令',
                  localAppName: '自定义调用头，可留空，编辑前注意备份注册表',
                  localAppUnknowCall: '无法分析此命令，请检查命令或者手动构造注册表',
                  localAppWrongName: '调用头只能输入数字或者字母',
                  callInputKey: '唤出搜索输入框的快捷键',
                  showAllKey: '唤出全部展开模式的快捷键',
                  defaultFindTab: '默认显示页内查找',
                  defaultFindTabTips: '打开搜索输入框时默认显示页内查找标签，否则默认显示站点筛选标签',
                  globalSearchNow: '立即搜索所有标签页',
                  globalSearchNowTips: '当点击固定按钮时，立即在所有标签页搜索关键词，否则仅搜索当前活动标签页，可能会影响性能，谨慎开启',
                  geneRegFile: '生成注册表补丁',
                  targetTxt: '划词搜索分组',
                  targetImg: '以图搜图分组',
                  targetLink: '链接处理分组',
                  targetPage: '当前页面分组',
                  dragHistory: '拖拽轮盘外圈',
                  hideDragHistoryTips: '隐藏拖拽轮盘中用于存放最近 10 个历史访问引擎的外圈',
                  reuseDragHistoryTips: '拖拽轮盘外圈继续显示当前分组超出 6 个之外的引擎',
                  disableAutoOpen: '禁用分组自动展开',
                  disableAutoOpenTips: '启用后，调出搜索条之后，对应分组将不再自动展开',
                  minPopup: '最小化搜索磁贴',
                  minPopupTips: '启用后，划词磁贴将只显示一个分组图标，直至鼠标划过',
                  minPopupDisable: '禁用',
                  minPopupEnable: '启用',
                  minPopupInput: '仅在输入框上启用',
                  hidePopup: '禁用搜索磁贴',
                  hidePopupTips: '开启后，划词磁贴将会禁用，划词时以完整搜索条取代',
                  numPerLine: '磁贴每行引擎数',
                  numPerLineTips: '设置磁贴每一行显示的引擎数量',
                  limitPopupLen: '划词磁贴字数限制',
                  limitPopupLenTips: '当划选文字长度小于此字数时不显示磁贴',
                  hideOnSearchEngine: '在搜索引擎页面隐藏',
                  hideOnSearchEngineTips: '启用后，在搜索引擎页面搜索条将不再自动显示',
                  suggestType: '搜索联想词的引擎',
                  templateTitle: '模板文本',
                  templateTips: '模板文本，用 $template{模板名} 调用',
                  templateName: '模板名',
                  templateValue: '模板内容',
                  paramTitle: '搜索参数',
                  param: '参数',
                  details: '详述',
                  param_s: '搜索关键词',
                  param_S: '最近一次的搜索关键词',
                  param_sl: '小写字母搜索词',
                  param_su: '大写字母搜索词',
                  param_sr: '未转码的搜索关键词',
                  param_ss: '搜索关键词转换为简体中文，需要安装我的【简繁自由切换】 https://greasyfork.org/scripts/24300',
                  param_st: '搜索关键词转换为繁体中文，同上',
                  param_se: '搜索关键词执行 escape',
                  param_e: '当前页面编码',
                  param_c: '客户端: pc,mobile',
                  param_u: '当前网站 url，指向链接或图片时为对应 url。%U: 该项的 URI 编码',
                  param_h: '当前网站 host',
                  param_t: '当前指向链接或者图片的地址。%T: 该项的 URI 编码',
                  param_b: '指向对象地址去除 http头。%B: 该项的 URI 编码',
                  param_n: '指向对象的 title 或 alt 或 网站标题',
                  param_i: '指向图片的 base64，未指向图片时尝试获取剪贴板图片',
                  param_sre: '用正则替换搜索关键词/页面或链接url/图片src，例如 %sr.replace(/[^\\d]/g, "").replace(/(\\d)/g, "$1 ") 代表提取原始关键词中所有数字，并以空格分隔，支持 %s %sl %sr %su %t %u',
                  param_ssplit: '多行搜索参数，%s[]代表按换行或者空格分隔后依次取下一项，%s[-1]代表逆序依次取下一项，%s[0]代表指定第一项，%s[all]代表分隔后批量搜索，%s[1|@]代表以@分隔并且指定第二项，支持replace，例如%s[].replace(/(\\d)/,"a$1")。没有关键词时会尝试读取剪贴板',
                  param_p1: 'post 参数体，例如 %p{x=1&y=%s}',
                  param_p2: 'post 但不跳转',
                  param_p3: '页内 post，可在页面之内使用【css 选择器或者 xpath】填写参数提交查询，适用于不开放GET/POST接口的网站，例如 #p{#input=%u&sleep(500)&click(.submit)}, 代表在"#input"内输入指定url，然后等待500毫秒，最后点击".submit"。可在内容中使用 \\& \\= 来 表示 & =。wait(#input) 代表等待元素 #input 出现，wait(!.loading)代表等待元素 .loading 消失，call(alert("Hello")) 代表执行代码 alert("Hello")，支持 await。input 时 @ 代表当前输入框',
                  param_input: '输入占位，例如%input{请输入您的三围,90 55 90}。使用/创建下拉菜单，例如%input{请选择你的罩杯,A/B/C}。也可以分别添加描述，例如%input{请选择你的罩杯/稀有/绝佳/好大,A/B/C}',
                  param_group: '通过你已经创建的站点名批量打开，例如 ["雅虎搜索","谷歌搜索"]',
                  param_ele: '通过 css 选择器或者 xpath 抓取元素并返回文字内容，例如 %element{.mainTitle}，省略选择器时返回当前选中元素',
                  param_elep: '获取抓取到元素的属性值，例如 %element{.mainTitle}.prop(href) %element{.mainTitle}.prop(innerHTML)',
                  param_elere: '正则替换，例如 %element{.mainTitle}.prop(href).replace(/https/i,"")',
                  param_cp: '在开头使用"copy:"可以复制之后的所有字串',
                  param_showTips: '在鼠标悬浮时立即在 tips 内显示所获取的 html 代码，如果返回数组则第二项为点击后复制的内容，第二项返回链接则点击后打开。可使用 fetch 跨域，使用 storage.getItem/storage.setItem 操作持久数据，name 获取引擎名。也可以使用简化模式，直接传入链接与模板，例如 showTips:https://api.xxx.xxx/xxx <i>{json.result|*%s} USD = %s RMB</i>，代表抓取 api.xxx.xxx 的数据，以 json 格式解析，并将 json.result 放入 <i> 模板后返回 tips。再例如 showTips:https://xxx.com/%sr <span>{title}</span><p>{.genre a|<mark>()</mark>}</p><img src="https://xxx.com{a.bigImage>img|src}"/> 代表抓取 xxx.com，获取页面标题、遍历所有 .genre a 元素的内容并分别创建 mark 元素、获取 a.bigImage>img 图片的 src 并创建 img 元素',
                  param_find: '页内查找高亮，例如 find:%s',
                  param_findadd: '添加目标关键词到指定页内高亮预置分组，例如 find.addto(reddit):%t.replace(/.*user/,"") 代表获取指定链接之后提取链接中 user 后参数添加进入 reddit 分组',
                  javascript: '执行 js 代码，window.keywords 代表关键词，window.targetElement 代表指向元素。如果当前页面无法执行页内代码，则可新建油猴脚本粘贴代码，导出方法到 window 下，通过方法名调用。例如 javascript:searchJumper_Function1',
                  param_date1: '当前时间戳（ms）',
                  param_date2: '对当前时间戳进行简单运算，例如%date{/1000 +604800}，代表一星期之后以秒计算的时间戳',
                  aboutContent: '平时工作中搜索引擎跳转功能用得很频繁，但尝试了相关的扩展，发现大多夹有私货。特别是国内公司做的插件，基本都有购物返链和隐私数据收集。\n而这只是一个简单功能，所以不如自己写一个啦。\n结果写配置页面耗费的精力数倍于脚本本身……🤦‍\n这个搜索引擎跳转支持自己拖拽定义位置，同时也支持站内搜索，多语言编码设置（例如shift-jis），划词搜索，以及配置导入导出。'
              }
              break;
          case 'zh-TW':
          case 'zh-HK':
              config = {
                  name: '搜尋醬',
                  lang: '語言',
                  setLang: '設置語言',
                  outOfDate: '發現新版本，點擊前往更新',
                  description: '詳細描述',
                  moreOptions: '更多選項',
                  showIcon: '顯示分組',
                  hideIcon: '隱藏分組',
                  rulesStore: '搜尋引擎倉庫',
                  import: '導入設置',
                  importFromClipboard: '從剪貼板導入',
                  exportTitle: '導出配置，單擊導出搜尋引擎配置，長按導出完整配置',
                  exportCache: '導出圖標緩存',
                  general: '常規設置',
                  searchEngines: '搜尋引擎',
                  exportConfig: '導出設置',
                  presetGroupName: '預置分組名',
                  presetGroupValue: '預置分組內容',
                  addGroup: '添加預置分組',
                  addGroupTips: '添加一組預置高亮詞，以在不同場景重複調用',
                  findInPage: '頁内查找',
                  customSearch: '劃詞搜尋',
                  about: '關於',
                  showInSearchEngine: '高亮搜尋引擎頁面',
                  showInSearchEngineTips: '在搜尋引擎結果頁高亮關鍵詞',
                  showInSearchJumpPage: '高亮搜尋引擎頁面開啟的站點',
                  showInSearchJumpPageTips: '在搜尋引擎頁面點選開啟的站點內高亮關鍵詞',
                  currentTypeFirst: '置頂當前分組',
                  currentTypeFirstTips: '開啟後，當前分組將前移至第一位',
                  mouseLeaveToHide: '滑鼠移開時自動隱藏',
                  mouseLeaveToHideTips: '當滑鼠從搜索條或者搜索磁貼上移開時自動隱藏搜尋醬',
                  limitInPageLen: '限制關鍵詞最小長度',
                  limitInPageLenTips: '不對長度小於此值的關鍵詞進行高亮',
                  ignoreWords: '忽略關鍵詞列表',
                  inPageWordsStyles: '關鍵詞樣式',
                  inPageWordsAddStyles: '自定義關鍵詞CSS，數組内按順序指向對應關鍵詞',
                  defaultPicker: '自動開啟元素選擇',
                  defaultPickerTips: '打開搜尋輸入框時自動開啟元素選擇',
                  emptyAfterCloseInput: '關閉時清空高亮',
                  emptyAfterCloseInputTips: '關閉搜尋輸入框時清空高亮關鍵字',
                  altToHighlight: 'Alt 劃選立即高亮',
                  altToHighlightTips: '使用搜索輸入框的頁內搜尋功能時，使用 Alt 劃選後立即高亮',
                  disableInputOnWords: '劃選文字時不彈出搜尋輸入框',
                  disableInputOnWordsTips: '正在劃選文字時使用快捷鍵不彈出搜尋輸入框，僅顯示搜尋條',
                  inPageRule: '站點自動高亮規則',
                  errorNoType: '請輸入分組名',
                  errorSameType: '分組名不能重複',
                  editType: '編輯分組',
                  typeName: '分組名',
                  typeIcon: '分組圖標',
                  category: '分組',
                  iconTips: '圖標可使用 FontAwsome、圖片連結或者 base64 代碼',
                  typeMatch: '根據網址篩選當前分組，設爲 0 隱藏該分組',
                  typeEnableSelTxt: '對選擇文字生效',
                  typeEnableSelImg: '對圖片生效',
                  typeEnableSelAudio: '對音頻生效',
                  typeEnableSelVideo: '對視頻生效',
                  typeEnableSelLink: '對鏈接生效',
                  typeEnableSelPage: '對頁面生效',
                  typeOpenInNewTab: '啟用後該組連結將默認在新窗口打開',
                  openSelect: '打開選項',
                  openInNewTabOption: '新標簽頁打開',
                  openInCurrentOption: '當前頁打開',
                  openInDefaultOption: '默認打開選項',
                  showCurrent: '顯示當前站點',
                  showCurrentTips: '匹配到當前站點時，不隱藏當前站點圖標',
                  delete: '刪除',
                  deleteOk: '刪除完畢',
                  cancel: '取消',
                  edit: '編輯',
                  add: '新增',
                  editSite: '編輯站點',
                  addSite: '新增站點',
                  addType: '新增分組',
                  siteName: '站點名',
                  siteUrl: '站點 URL',
                  siteIcon: '站點圖標',
                  siteKeywords: '搜尋詞提取',
                  keywordRegTips: '單個關鍵詞：wd；多個：wd|qw|key；正則分組：(?:wd|w)/(.*?)\\b；選擇器：input#su',
                  kwFilter: '搜尋詞或者指向連結的篩選正則',
                  kwFilterTips: '當對象文字或者連結不匹配正則時隱藏該引擎',
                  siteMatch: '根據頁面網址的正則匹配當前引擎，設爲 0 强制隱藏該站',
                  siteCharset: '站點編碼',
                  toolbarPosition: '工具欄位置',
                  portrait: '縱向',
                  horizontal: '橫向',
                  openInNewTab: '默認在新標籤頁打開連結',
                  openInNewTabTips: '啟用後連結將全部默認在新標籤頁打開',
                  enableInPage: '啟用劃詞搜尋',
                  enableInPageTips: '啟用後選擇文字並長按滑鼠右鍵可調出工具長條',
                  bindFunctionKey: '按住此功能鍵單擊滑鼠右鍵可立即喚出當前分組的磁貼',
                  ctrlKey: 'Ctrl鍵',
                  altKey: 'Alt鍵',
                  shiftKey: 'Shift鍵',
                  metaKey: 'meta鍵',
                  configContent: '設置源碼',
                  batchOpenConfirm: '批量搜尋確認框',
                  batchOpenConfirmDefault: '默認',
                  batchOpenConfirmAlways: '總是需要確認',
                  batchOpenConfirmNo: '不需要確認',
                  copy: '複製',
                  save: '保存',
                  autoClose: '自動合上分組',
                  autoDelay: '隱藏延時',
                  needName: '需要名稱',
                  needUrl: '需要 URL',
                  wrongImg: '非有效圖標地址',
                  overOpen: '滑鼠划過時分組自動展開',
                  overOpenTips: '選中此項則當滑鼠划過分組圖標，對應分組將自動展開',
                  selectToShow: '劃選立即調用磁貼',
                  selectToShowTips: '啟用後劃選立即調出磁貼',
                  autoCloseTips: '啟用之後一旦滑鼠離開搜尋條，已打開的分組抽屜將會自動合上',
                  enableShortcut: '啟用站點快捷鍵',
                  enableShortcutTips: '啟用後，將使得所有為站點分配的快捷鍵生效',
                  shortcut: '快捷鍵',
                  siteShotcut: '搜尋快捷鍵',
                  switchSitesKey: '當前分組內引擎切換快捷鍵，僅當匹配到當前引擎時有效',
                  switchSitesPreKey: '向前切換快捷鍵',
                  switchSitesNextKey: '向後切換快捷鍵',
                  initShow: '默認拉出工具欄',
                  initShowTips: '打開頁面立即拉出工具欄，鼠標划過后再貼邊隱藏',
                  configPage: '預設設定頁',
                  configPageTips: '將目前頁面設為預設設定頁',
                  alwaysShow: '總是顯示工具欄',
                  alwaysShowTips: '即使沒有匹配到搜尋引擎也顯示工具欄',
                  presetCss: '預置樣式',
                  presetCssTips: '選擇后載入預置樣式',
                  customCss: '自定義樣式',
                  replaceCss: '確定要替換當前編輯的樣式嗎？',
                  enableInInput: '監聽輸入框',
                  enableInInputTips: '啓用後，在輸入框内生效',
                  fontAwesomeCss: 'FontAwesome CDN地址',
                  nobatch: '不參與批量打開',
                  hideNotMatch: '非當前引擎則隱藏該項',
                  typeMatchTips: '僅在匹配站點顯示該分組',
                  siteUrlTips: '%s 查詢詞; %t 目標連結; %u 頁面地址; %h 頁面域名',
                  customSize: '縮放工具欄',
                  tilesZoom: '縮放磁貼',
                  tipsZoom: '縮放提示文本',
                  zoomDrag: '縮放拖曳圓盤',
                  typeOpenTime: '分組展開耗時',
                  longPressTime: '長按時間',
                  typeShotcut: '批量打開快捷鍵',
                  enableRightMouse: '啟用滑鼠右鍵長按',
                  enableRightMouseTips: '啟用後，在目標對象上長按滑鼠右鍵可喚出搜尋條',
                  enableLeftMouse: '啟用滑鼠左鍵',
                  enableLeftMouseTips: '啟用後，在目標對象上單擊滑鼠左鍵也能喚出搜尋條',
                  enableMiddleMouse: '啟用滑鼠中鍵',
                  enableMiddleMouseTips: '啟用後，在目標對象上單擊滑鼠中鍵也能喚出搜尋條',
                  cacheSwitch: '緩存圖標',
                  sameSiteName: '在【#t#】下存在同名站點',
                  sameShortcut: '【#t#】已經綁定了相同快捷鍵',
                  noIcons: '純文本模式',
                  noIconsTips: '隱藏圖標，僅顯示純文本',
                  showEngineWords: '顯示引擎名',
                  showEngineWordsTips: '在引擎圖標下方顯示引擎名',
                  noAni: '禁止動畫效果',
                  noAniTips: '禁止所有動畫效果',
                  quickAddRule: '快速添加搜尋引擎',
                  quickAddRuleTips: '按住 Ctrl + Alt 點擊任意搜尋框快速添加搜尋引擎',
                  searchMycroft: '💎 在 mycroftproject 上搜尋其他人編輯好的搜尋引擎並一鍵導入',
                  showSiteLists: '顯示引擎列表',
                  showSiteListsTips: '啓用後將在分組圖標旁啓用引擎列表面板',
                  alwaysShowSiteLists: '總是顯示引擎列表',
                  alwaysShowSiteListsTips: '啟用後，分組抽屜打開時也會顯示引擎列表',
                  disableTypeOpen: '禁用分組點擊展開',
                  disableTypeOpenTips: '點擊分組后不再展開，而是顯示引擎列表',
                  historyLength: '歷史站點數',
                  historyLengthTips: '在默認展開的分組末尾插入數個最近訪問的站點',
                  historyInsertFirst: '將歷史站點插入到分組開頭',
                  historyInsertFirstTips: '將最近訪問的站點插入到分組開頭，否則插入到末尾',
                  shiftLastUsedType: '前移上次使用的分組',
                  shiftLastUsedTypeTips: '將上次使用的分組前移至當前分組之後',
                  sortType: '自動排序分組',
                  sortTypeTips: '自動按照訪問次數重新排序分組',
                  sortSite: '自動排序引擎',
                  sortSiteTips: '自動按照訪問次數重新排序分組内的引擎',
                  multiline: '多行搜尋，選取多行文字時，以換行符分隔，按行搜尋',
                  multilineLabel: '開關',
                  multilineGap: '搜尋間隔',
                  disable: '禁用',
                  enable: '啟用',
                  ask: '詢問',
                  filterEngine: '篩選引擎',
                  verifyResult: '驗證結果',
                  verifyBtn: '批量驗證所有引擎可用性',
                  verifying: '驗證中……',
                  verifyFinish: '驗證完成',
                  batchAction: '批量操作',
                  selectAll: '全選',
                  invert: '反選',
                  deleteConfirm: '你確定要刪除這些站點嗎？',
                  moveTo: '移動至',
                  moveToConfirm: '你確定要將這些站點移動至【#t#】嗎?',
                  autoHide: '自動隱藏搜尋條',
                  autoHideTips: '達到上方設置延時之後，自動隱藏搜尋條',
                  autoHideAll: '完全隱藏',
                  autoHideAllTips: '隱藏時使得搜尋條完全消失',
                  unsetTips: '未設置',
                  resizePageTips: '不隱藏並收縮頁面',
                  minSizeMode: '極簡模式',
                  minSizeModeTips: '開啟後，搜尋條將只顯示當前分組，直至鼠標劃過',
                  dragToSearch: '開啟拖拽搜尋',
                  dragToSearchTips: '開啟後拖曳文字、連結或者圖片進行搜尋，內圈為當前分組(即首個劃詞/搜圖/連結/頁面分組)前 6 個引擎，可自行前往搜尋引擎標籤頁修改，外圈為最近使用的引擎',
                  sameSiteUrl: '站點Url不能重複',
                  clone: '克隆',
                  cloneConfirm: '你確定要將這些站點克隆至 【#t#】?',
                  cloneAction: '你想要將它們克隆成一個集合嗎?',
                  groupName: '集合名',
                  donate: '你好！ 我是 Hoothin，也是 SearchJumper 的作者。 \n\n我很高興能與大家分享 SearchJumper，這是一個完全開源免費的專案。 雖然它的開發耗費了我大量的時間，但只要有人能從中獲得幫助，一切都是值得的。 \n\n如果您覺得 SearchJumper 對您有所幫助，並且願意支持我的努力，我真誠地希望您考慮以下幾種方式來誇誇我。 您的支持將是我前進的動力，讓我能夠繼續改進並提供更好的作品。 \n\n- 捐贈：您可以考慮透過捐贈來支持 SearchJumper 的未來發展。 即使是一小筆捐款，都將對我產生巨大的鼓舞和激勵。 \n- 回饋與分享：如果您有任何有關 SearchJumper 的回饋或建議，或願意與他人分享您的使用體驗，那將是我最開心的事情。 您的回饋將幫助我不斷改進和優化 SearchJumper，讓更多的人受益。 \n- 社區參與：歡迎加入 SearchJumper 的 Discord 頻道，與其他用戶分享您的見解和經驗。 這是一個互相學習和支持的平台，您的參與將使社區更加繁榮。 \n\n再次感謝您對 SearchJumper 的支持！ 我將竭盡全力優化改進這個項目。 謝謝您的捐款和誇獎，我由衷感激！ 💞',
                  importBookmarks: '導入瀏覽器書簽',
                  sync: 'Webdav 同步',
                  host: '伺服器地址',
                  username: '用戶名',
                  password: '密碼',
                  path: '路徑',
                  syncTips: 'Webdav 伺服器需要支援自設 cors，添加 allowed_hosts: https://hoothin.github.io',
                  expandType: '展開分組',
                  expandTypeTips: '展開分組，不隱藏同一分組中超出數量之外的引擎',
                  expandTypeLength: '顯示引擎數',
                  expandTypeLengthTips: '隱藏超出此數量的引擎',
                  jsonToolong: '站點數據過於龐大，是否繼續格式化為JSON文本？',
                  imgTooBig: '圖片大於50kb，是否繼續上傳？',
                  cacheSwitchTips: '在後台緩存圖標為base64圖片。注意開始緩存時會彈出跨域請求，緩存過程可能卡頓，此時勿關閉配置頁',
                  searchFontawesome: '🚩 搜尋 FontAwesome 圖標用於分組項',
                  localAppAddBtn: '添加自定義本地應用調用',
                  localApp: '本地應用調用',
                  localAppCall: '調用命令',
                  localAppName: '自定義調用頭，可留空，編輯前注意備份注冊表',
                  localAppUnknowCall: '無法分析此命令，請檢查命令或者手動構造註冊表',
                  localAppWrongName: '調用頭只能輸入數字或者字母',
                  callInputKey: '喚出搜尋輸入框的快捷鍵',
                  showAllKey: '喚出全部展開模式的快捷鍵',
                  defaultFindTab: '默認顯示頁內查找',
                  defaultFindTabTips: '打開搜尋輸入框時默認顯示頁內查找標簽，否則默認顯示站點篩選標簽',
                  globalSearchNow: '立即搜尋所有標籤頁',
                  globalSearchNowTips: '當點擊固定按鈕時，立即在所有標籤頁搜尋關鍵詞，否則僅搜尋當前活動標籤頁，可能會影響性能，謹慎開啟',
                  geneRegFile: '生成註冊表補丁',
                  targetTxt: '劃詞搜尋分組',
                  targetImg: '以圖搜圖分組',
                  targetLink: '鏈接處理分組',
                  targetPage: '當前頁面分組',
                  dragHistory: '拖曳輪盤外圈',
                  hideDragHistoryTips: '隱藏拖曳輪盤中用於存放最近 10 個歷史訪問引擎的外圈',
                  reuseDragHistoryTips: '拖曳輪盤外圈繼續顯示目前分組超出 6 個以外的引擎',
                  disableAutoOpen: '禁用分組自動展開',
                  disableAutoOpenTips: '啓用後，調出搜尋條之後，對應分組將不再自動展開',
                  minPopup: '最小化搜尋磁貼',
                  minPopupTips: '啟用後，劃詞磁貼將只顯示一個分組圖標，直至鼠標劃過',
                  minPopupDisable: '禁用',
                  minPopupEnable: '啟用',
                  minPopupInput: '僅在輸入框上啓用',
                  hidePopup: '禁用搜尋磁貼',
                  hidePopupTips: '開啟後，劃詞磁貼將會禁用，劃詞時以完整搜尋條取代',
                  numPerLine: '磁貼每行引擎數',
                  numPerLineTips: '設定磁貼每一行顯示的引擎數量',
                  limitPopupLen: '劃詞磁貼字數限制',
                  limitPopupLenTips: '當劃選文字長度小於此字數時不顯示磁貼彈框',
                  hideOnSearchEngine: '在搜尋引擎頁面隱藏',
                  hideOnSearchEngineTips: '啓用後，在搜尋引擎頁面搜尋條將不再自動顯示',
                  suggestType: '搜索聯想詞的引擎',
                  templateTitle: '模板文本',
                  templateTips: '模板文本，用 $template{模板名} 調用',
                  templateName: '模板名',
                  templateValue: '模板内容',
                  paramTitle: '搜尋參數',
                  param: '參數',
                  details: '詳述',
                  param_s: '搜尋關鍵詞',
                  param_S: '最近一次的搜尋關鍵詞',
                  param_sl: '小寫字母搜尋詞',
                  param_su: '大寫字母搜尋詞',
                  param_sr: '未轉碼的搜尋關鍵詞',
                  param_ss: '搜尋關鍵詞轉換爲簡體中文，需要安裝我的【繁簡自由切換】 https://greasyfork.org/scripts/24300',
                  param_st: '搜尋關鍵詞轉換爲正體中文，同上',
                  param_se: '搜尋關鍵詞執行 escape',
                  param_e: '當前頁面編碼',
                  param_c: '客戶端: pc,mobile',
                  param_u: '當前網站 url，指向鏈接或圖片時為對應 url。%U: 該項的 URI 編碼',
                  param_h: '當前網站 host',
                  param_t: '當前指向鏈接或者圖片的地址。%T: 該項的 URI 編碼',
                  param_b: '指向對像地址去除 http頭。%B: 該項的 URI 編碼',
                  param_n: '指向對像的 title 或 alt 或 網站標題',
                  param_i: '指向圖片的 base64，未指向圖片時嘗試取得剪貼簿圖片',
                  param_sre: '用正則替換搜尋關鍵詞/頁面或鏈接url/圖片src，例如 %sr.replace(/[^\\d]/g, "").replace(/(\\d)/g, "$1 ") 代表提取原始關鍵詞中所有數字，並以空格分隔，支持 %s %sl %sr %su %t %u',
                  param_ssplit: '多行搜尋參數，%s[]代表按換行或者空格分隔後依次取下一項，%s[-1]代表逆序依次取下一項，%s[0]代表指定第一項，%s[all]代表分隔後批量搜尋，%s[1|@]代表以@分隔並且指定第二項，支持replace，例如%s[].replace(/(\\d)/,"a$1")。沒有關鍵詞時會嘗試讀取剪貼板',
                  param_p1: 'post 參數體，例如 %p{x=1&y=%s}',
                  param_p2: 'post 但不跳轉',
                  param_p3: '頁内 post，可在頁面之内使用【css 選擇器或者 xpath】填寫參數提交查詢，適用於不開放GET/POST接口的網站，例如 #p{#input=%u&sleep(500)&click(.submit)}, 代表在"#input"内輸入指定url，然後等待500毫秒，最後點擊".submit"。可在内容中使用 \\& \\= 來 表示 & =。wait(#input) 代表等待元素 #input 出現，wait(!.loading)代表等待元素 .loading 消失，call(alert("Hello")) 代表執行程式碼 alert("Hello")，支援 await。input 時 @ 代表當前輸入框',
                  param_input: '輸入占位，例如%input{請輸入您的三圍,90 55 90}。使用/創建下拉菜單，例如%input{請選擇你的罩杯,A/B/C}。也可以分別添加描述，例如%input{請選擇你的罩杯/稀有/絕佳/好大,A/B/C}',
                  param_group: '透過你已經創建的站點名批量打開，例如 ["雅虎搜尋","谷歌搜尋"]',
                  param_ele: '透過 css 選擇器或者 xpath 抓取元素並返回文字内容，例如 %element{.mainTitle}，省略選擇器時返回當前選中元素',
                  param_elep: '獲取抓取到元素的屬性值，例如 %element{.mainTitle}.prop(href) %element{.mainTitle}.prop(innerHTML)',
                  param_elere: '正則替換，例如 %element{.mainTitle}.prop(href).replace(/https/i,"")',
                  param_cp: '在開頭使用"copy:"可以複製之後的所有字串',
                  param_showTips: '在鼠標懸浮時立即在 tips 內顯示所獲取的 html 代碼，如果返回陣列則第二項為點擊後復制的內容，第二項返回連結則點擊后打開。可使用 fetch 跨域，使用 storage.getItem/storage.setItem 操作持久數據，name 獲取引擎名。也可以使用簡化模式，直接傳入鏈接與模板，例如 showTips:https://api.xxx.xxx/xxx <i>{json.result|*%s} USD = %s RMB</i>，代表抓取 api.xxx.xxx 的數據，以 json 格式解析，並將 json.result 放入 <i> 模板後返回 tips。再例如 showTips:https://xxx.com/%sr <span>{title}</span><p>{.genre a|<mark>()</mark>}</p><img src="https://xxx.com{a.bigImage>img|src}"/> 代表抓取 xxx.com，獲取頁面標題、遍歷所有 .genre a 元素的內容並分別創建 mark 元素、獲取 a.bigImage>img 圖片的 src 並創建 img 元素',
                  param_find: '頁內查找高亮，例如 find:%s',
                  param_findadd: '添加目標關鍵詞到指定頁內高亮預置分組，例如 find.addto(reddit):%t.replace(/.*user/,"") 代表獲取指定鏈接之後提取鏈接中 user 後參數添加進入 reddit 分組',
                  javascript: '執行 js 程式碼，window.keywords 代表關鍵字，window.targetElement 代表指向元素。 如果目前頁面無法執行頁內程式碼，則可新建油猴腳本貼上程式碼，匯出方法到 window 下，透過方法名稱呼叫。 例如 javascript:searchJumper_Function1',
                  param_date1: '當前時間戳（ms）',
                  param_date2: '對當前時間戳進行簡單運算，例如%date{/1000 +604800}，代表一星期之後以秒計算的時間戳',
                  aboutContent: '平時工作中搜尋引擎跳轉功能用得很頻繁，但嘗試了相關的擴展，發現大多夾有私貨。\n而這只是一個簡單功能，所以不如自己寫一個啦。\n結果寫配置頁面耗費的精力數倍於腳本本身……🤦‍\n這個搜尋引擎跳轉支持自己拖拽定義位置，同時也支持站內搜尋，多語言編碼設置（例如shift-jis），劃詞搜尋，以及配置導入導出。'
              }
              break;
          default:
              config = {
                  name: 'SearchJumper',
                  lang: 'Language',
                  setLang: 'Set language',
                  outOfDate: 'The script is out of date, click to update',
                  description: 'Description',
                  moreOptions: 'More options',
                  showIcon: 'Show category',
                  hideIcon: 'Hide category',
                  rulesStore: 'Search engine Store',
                  import: 'Import config',
                  importFromClipboard: 'Import from clipboard',
                  exportTitle: 'Export JSON, click to export engines, hold to export all config data',
                  exportCache: 'Export icon cache',
                  general: 'General',
                  searchEngines: 'Search Engines',
                  exportConfig: 'Export Config',
                  presetGroupName: 'Preset group name',
                  presetGroupValue: 'Preset group content',
                  addGroup: 'Add preset group',
                  addGroupTips: 'Add a set of preset highlight words to be called repeatedly in different scenes',
                  findInPage: 'Find In Page',
                  customSearch: 'Custom Search',
                  about: 'About',
                  showInSearchEngine: 'Highlight search engine page',
                  showInSearchEngineTips: 'Highlight keywords on the search engine results page',
                  showInSearchJumpPage: 'Highlight the site opened from the search engine',
                  showInSearchJumpPageTips: 'Highlight keywords on the page opened by click on the search engine',
                  currentTypeFirst: 'Stick current group',
                  currentTypeFirstTips: 'After enabled, current group will move to the first position',
                  mouseLeaveToHide: 'Automatically hide when mouse leaves',
                  mouseLeaveToHideTips: 'Automatically hide when mouse moves away from the search bar',
                  limitInPageLen: 'Limit the minimum length of keywords',
                  limitInPageLenTips: 'Do not highlight keywords whose length is less than this value',
                  ignoreWords: 'Ignore keyword list',
                  inPageWordsStyles: 'Keyword styles',
                  inPageWordsAddStyles: 'Custom keyword CSS, input an array target each keyword',
                  defaultPicker: 'Auto enable element selection',
                  defaultPickerTips: 'Automatically enable element selection when opening the search input box',
                  emptyAfterCloseInput: 'Clear the highlight when closing',
                  emptyAfterCloseInputTips: 'Clear the highlighted keywords when closing the search input box',
                  altToHighlight: 'Alt swipe to highlight immediately',
                  altToHighlightTips: 'When using the in-page search function under search input, highlight immediately with Alt after selection',
                  disableInputOnWords: 'No search input when something is selected',
                  disableInputOnWordsTips: 'Do not pop up the search input with shortcut key when something is selected',
                  inPageRule: 'Site auto-highlighting rules',
                  errorNoType: 'Please enter the category name',
                  errorSameType: 'Found same category name',
                  editType: 'Edit category',
                  typeName: 'Category name',
                  typeIcon: 'Category icon',
                  category: 'Category',
                  iconTips: 'The icon can use FontAwsome, image link or base64 code',
                  typeMatch: 'Filter current group by url, hide by set to 0',
                  typeEnableSelTxt: 'Effect on text',
                  typeEnableSelImg: 'Effect on image',
                  typeEnableSelAudio: 'Effect on audio',
                  typeEnableSelVideo: 'Effect on video',
                  typeEnableSelLink: 'Effect on link',
                  typeEnableSelPage: 'Effect on page',
                  typeOpenInNewTab: 'After enabling, this group of links will be opened in a new window by default',
                  openSelect: 'Open mode',
                  openInNewTabOption: 'Open in new tab',
                  openInCurrentOption: 'Open in current',
                  openInDefaultOption: 'Open by default',
                  showCurrent: 'Show current site',
                  showCurrentTips: 'Show the site button of current when matched',
                  delete: 'Delete',
                  deleteOk: 'Delete over',
                  cancel: 'Cancel',
                  edit: 'Edit',
                  add: 'Add',
                  editSite: 'Edit site',
                  addSite: 'Add site',
                  addType: 'Add type',
                  siteName: 'Site name',
                  siteUrl: 'Site URL',
                  siteIcon: 'Site icon',
                  siteKeywords: 'Extract search keywords',
                  keywordRegTips: 'Single: wd, Multiple: wd|qw|key, RegExp group: (?:wd|w)/(.*?)\\b, Selector: input#su',
                  kwFilter: 'Filter search keywords or url',
                  kwFilterTips: 'Hide the engine when the object words or target url does not match this regex',
                  siteMatch: 'URL RegExp of site for matching engine, force hide by set to 0',
                  siteCharset: 'Charset',
                  toolbarPosition: 'Toolbar position',
                  portrait: 'Portrait',
                  horizontal: 'Horizontal',
                  openInNewTab: 'Open links in new tabs by default',
                  openInNewTabTips: 'When enabled, the link will be opened in a new tab by default',
                  enableInPage: 'Enable select to search',
                  enableInPageTips: 'After enabling, select some text and long press the right mouse to bring up the toolbar',
                  bindFunctionKey: 'Right click with this function key to call out search tiles without long press',
                  ctrlKey: 'Ctrl key',
                  altKey: 'Alt key',
                  shiftKey: 'Shift key',
                  metaKey: 'Meta key',
                  configContent: 'Config source code',
                  batchOpenConfirm: 'Batch search confirm',
                  batchOpenConfirmDefault: 'Default',
                  batchOpenConfirmAlways: 'Always confirm',
                  batchOpenConfirmNo: 'Without confirm',
                  copy: 'Copy',
                  save: 'Save',
                  autoClose: 'Auto close type',
                  autoDelay: 'Hide delay',
                  needName: 'Require name',
                  needUrl: 'Require url',
                  wrongImg: 'Wrong icon',
                  overOpen: 'Mouse over to expand category automatically ',
                  overOpenTips: 'If you select this item, when the mouse moves over the category icon, the corresponding category will be automatically expanded',
                  selectToShow: 'Select to call tiles',
                  selectToShowTips: 'After enabling, select to bring up the tiles immediately',
                  autoCloseTips: 'When enabled, opened category drawer will be closed automatically once the mouse leaves the search bar',
                  enableShortcut: 'Enable site shortcuts',
                  enableShortcutTips: 'After enabling, all shortcut keys assigned to single site will take effect',
                  shortcut: 'Shortcut key',
                  siteShotcut: 'Search shortcut key',
                  switchSitesKey: 'Shortcut key for engine switching in the current group, only valid when matching',
                  switchSitesPreKey: 'Switch prev key',
                  switchSitesNextKey: 'Switch next key',
                  initShow: 'Init show',
                  initShowTips: 'Pull out to show when page initializes',
                  configPage: 'Default settings page',
                  configPageTips: 'Set the current page as the default settings page',
                  alwaysShow: 'Always show toolbar',
                  alwaysShowTips: 'Show toolbar even if no search engine matches',
                  presetCss: 'Preset Css',
                  presetCssTips: 'Select to load preset css',
                  customCss: 'Custom Css',
                  replaceCss: 'Do you confirm to replace current css?',
                  enableInInput: 'Enable on input',
                  enableInInputTips: 'Enable SearchJumper on input or textarea',
                  fontAwesomeCss: 'FontAwesome CDN URL',
                  nobatch: 'Do not open when batch open',
                  hideNotMatch: 'Hide if not current',
                  typeMatchTips: 'Show this category only when url matches',
                  siteUrlTips: '%s keywords; %t target URL; %u site URL; %h hostname',
                  customSize: 'Zoom toolbar',
                  tilesZoom: 'Zoom tiles',
                  tipsZoom: 'Zoom tips',
                  zoomDrag: 'Zoom drag disc',
                  typeOpenTime: 'Category expansion time',
                  longPressTime: 'Long press time',
                  typeShotcut: 'Shortcut for batch open',
                  enableRightMouse: 'Effect with right mouse',
                  enableRightMouseTips: 'Effect after long press the right mouse button on target',
                  enableLeftMouse: 'Effect with left mouse',
                  enableLeftMouseTips: 'Also effect after single click the left mouse button on target words',
                  enableMiddleMouse: 'Effect with middle mouse',
                  enableMiddleMouseTips: 'Also effect after single click the middle mouse button on target words',
                  cacheSwitch: 'Cache icons',
                  sameSiteName: 'Site under 【#t#】 has the same name',
                  sameShortcut: '【#t#】 has already bind the same shortcut',
                  noIcons: 'Plain text mode',
                  noIconsTips: 'Show only plain text without any icon',
                  showEngineWords: 'Show engine name',
                  showEngineWordsTips: 'Show name beside the engine icon',
                  noAni: 'Disable animation effects',
                  noAniTips: 'Disable all animation effects',
                  quickAddRule: 'Quick Add Site',
                  quickAddRuleTips: 'Click any search input box with Ctrl + Alt to add site quickly',
                  searchMycroft: '💎 Search site config on mycroftproject for import by one click',
                  showSiteLists: 'Show drop-down list',
                  showSiteListsTips: 'After enabled, the drop-down list will be enabled next to the category icon',
                  alwaysShowSiteLists: 'Always show drop-down lists',
                  alwaysShowSiteListsTips: 'After enabled, the drop-down list will be enabled even when category opened',
                  disableTypeOpen: 'Disable category click-to-expansion',
                  disableTypeOpenTips: 'After enabling, when the category icon is clicked, it will no longer be expanded',
                  historyLength: 'Number of history sites',
                  historyLengthTips: 'Insert several recently visited sites at the end of current expanded category',
                  historyInsertFirst: 'Insert the history sites at the beginning of current group',
                  historyInsertFirstTips: 'Insert the most recently visited sites at the beginning of the group, otherwise at the end',
                  shiftLastUsedType: 'Move forward the last used category',
                  shiftLastUsedTypeTips: 'Move the last used group forward after the current category',
                  sortType: 'Auto sort categories',
                  sortTypeTips: 'Automatically reorder categories according to the number of visits',
                  sortSite: 'Auto sort engines',
                  sortSiteTips: 'Automatically reorder engines in category according to the number of visits',
                  multiline: 'Multi-line text search, separated by line feed, search by single line',
                  multilineLabel: 'Switch',
                  multilineGap: 'Search Gap',
                  disable: 'Disable',
                  enable: 'Enable',
                  ask: 'Ask',
                  filterEngine: 'Filter engine',
                  verifyResult: 'Verify result',
                  verifyBtn: 'Verify availability of all engines',
                  verifying: 'Verifying...',
                  verifyFinish: 'Verify complete',
                  batchAction: 'Batch Action',
                  selectAll: 'Select All',
                  invert: 'Invert',
                  deleteConfirm: 'Do you want to delete these sites?',
                  moveTo: 'Move to',
                  moveToConfirm: 'Do you want to move these sites to 【#t#】?',
                  autoHide: 'Auto hide bar',
                  autoHideTips: 'Auto hide search bar after hide delay set before',
                  autoHideAll: 'Completely hide',
                  autoHideAllTips: 'Hide the search bar completely',
                  unsetTips: 'Unset',
                  resizePageTips: 'Resize page without hide',
                  minSizeMode: 'Minimalist Mode',
                  minSizeModeTips: 'After opening, the search bar will only display the current category until the mouse is over',
                  dragToSearch: 'Enable drag to search',
                  dragToSearchTips: 'Drag text, link or image to search quickly, the inner circle contains the top 6 engines in the current group(first text/image/link group), and the outer circle contains the most recently used engines',
                  sameSiteUrl: 'Found a site with same url',
                  clone: 'Clone',
                  cloneConfirm: 'Do you want to clone these sites to 【#t#】?',
                  cloneAction: 'Do you want to clone as one group instead of a single site?',
                  groupName: 'Group Name',
                  donate: 'Hello there! I\'m Hoothin, the author of SearchJumper.\n\nI\'m delighted to share SearchJumper with all of you. It\'s a completely open-source and free project. Despite the considerable amount of time I\'ve invested in its development, knowing that it\'s been helpful to you makes it all worthwhile.\n\nIf you\'ve found SearchJumper beneficial and would like to support my efforts, I genuinely appreciate your consideration of the following ways to give me a shoutout. Your support will motivate me to keep improving and providing a better service.\n\n- Donations: You may consider making a donation to support the future development of SearchJumper. Even a small contribution will greatly encourage and inspire me.\n- Feedback and Sharing: If you have any feedback or suggestions regarding SearchJumper or would like to share your user experience with others, it would make me incredibly happy. Your feedback will help me continuously improve and optimize SearchJumper for the benefit of more people.\n- Community Engagement: You are welcome to join the Discord channel and share your insights and experiences with other users. It\'s a platform for mutual learning and support, and your participation will contribute to its thriving.\n\nOnce again, thank you for your support of SearchJumper! I\'m committed to providing you with an enhanced help and continuously working on improving this project. Thank you for your donations and kind words; I truly appreciate them! 💞',
                  importBookmarks: 'Import browser bookmarks',
                  sync: 'Sync by Webdav',
                  host: 'Host',
                  username: 'Username',
                  password: 'Password',
                  path: 'Path',
                  syncTips: 'Webdav server need to support custom cors, add allowed_hosts: https://hoothin.github.io',
                  expandType: 'Expand group',
                  expandTypeTips: 'Expand group, Do not collapse engines in one group',
                  expandTypeLength: 'Show engines number',
                  expandTypeLengthTips: 'Hide the engines more than this number',
                  jsonToolong: 'The sites data is too long, do you want to continue format to json?',
                  imgTooBig: 'Image is larger than 50kb, still want to upload?',
                  cacheSwitchTips: 'The icons will be cached with base64 images in the background, some cross-domain requests will pop up after cache action started',
                  searchFontawesome: '🚩 Search icons for category from FontAwesome.com',
                  localAppAddBtn: 'Call local application',
                  localApp: 'Local application call',
                  localAppCall: 'Call command',
                  localAppName: 'Custom call header, can be left blank',
                  localAppUnknowCall: 'Unable to parse this command, please check the command or manually construct the registry',
                  localAppWrongName: 'The call header can only enter with numbers or letters',
                  callInputKey: 'Shortcut key for calling out the search input',
                  showAllKey: 'Shortcut key for calling out Show-All-Mode',
                  defaultFindTab: 'Default to display find in page',
                  defaultFindTabTips: 'When the search input is opened, the find-in-page will be displayed by default, otherwise the site filter will be displayed by default',
                  globalSearchNow: 'Search all tabs immediately',
                  globalSearchNowTips: 'When clicking on Pin button for highlighted word, immediately search for keywords in all tabs, which may affect performance, open with caution',
                  geneRegFile: 'Generate registry patch',
                  targetTxt: 'Words search',
                  targetImg: 'Image search',
                  targetLink: 'Link Search',
                  targetPage: 'Current page',
                  dragHistory: 'Outer ring of the drag wheel',
                  hideDragHistoryTips: 'Hide the outer ring of the drag wheel which storing the last 10 historically visited sites',
                  reuseDragHistoryTips: 'Continues to display engines beyond 6 of current group in the outer ring of the drag wheel',
                  disableAutoOpen: 'Disable category auto-expansion',
                  disableAutoOpenTips: 'After enabling, when Search Bar is called up, Category will no longer be expanded automatically',
                  minPopup: 'Minimize the search popup',
                  minPopupTips: 'When enabled, the popup box will only display a category icon until the mouse is over',
                  minPopupDisable: 'Disable',
                  minPopupEnable: 'Enable',
                  minPopupInput: 'Only on input',
                  hidePopup: 'Disable search popup',
                  hidePopupTips: 'After opening, the popup box will be disabled, and the full search bar will be used to replace it',
                  numPerLine: 'Number of engines per line of tile',
                  numPerLineTips: 'Set the number of engines displayed in each line of the tile',
                  limitPopupLen: 'Limit words for popup',
                  limitPopupLenTips: 'No popup box when length of selected words is less than this',
                  hideOnSearchEngine: 'Hide on search engine page',
                  hideOnSearchEngineTips: 'After enabling, Search Bar on the search engine page will no longer be displayed automatically',
                  suggestType: 'Source of related words',
                  templateTitle: 'Template text',
                  templateTips: 'Template text, call by $template{template name}',
                  templateName: 'Template Name',
                  templateValue: 'Template Value',
                  paramTitle: 'Search params',
                  param: 'Param',
                  details: 'Details',
                  param_s: 'Search keyword',
                  param_S: 'Cached search keyword',
                  param_sl: 'Search keyword with lower case letters',
                  param_su: 'Search keyword with upper case letters',
                  param_sr: 'Search keyword without doing any encoding',
                  param_ss: 'Search keyword to Simplified Chinese, need to work with my 【Switch Traditional Chinese and Simplified Chinese】 https://greasyfork.org/scripts/24300',
                  param_st: 'Search keyword to Traditional Chinese, same as above',
                  param_se: 'Search keyword with escape encoding',
                  param_e: 'Charset',
                  param_c: 'Client: pc,mobile',
                  param_u: 'Current website url, when pointing to a link or picture, it means the corresponding url. %U: with encodeURIComponent',
                  param_h: 'Current website host',
                  param_t: 'The address of target link or image. %T: with encodeURIComponent',
                  param_b: 'Target address without http. %B: with encodeURIComponent',
                  param_n: 'Title or alt of target or title of current page',
                  param_i: 'Base64 of target image. If the target is not image, will try to get the clipboard image',
                  param_sre: 'Replace keywords/url/src with regexp, like %sr.replace(/[^\\d]/g, "").replace(/(\\d)/g, "$1 ") means replace raw keywords to numbers and then join all numbers with space, support %s %sl %sr %su %t %u',
                  param_ssplit: 'Multi-line search parameters, %s[] means to select the next item in sequence after being separated by newline or space, %s[-1] means to get the next item in reverse order, %s[0] means to specify the first item, %s[all] means to batch search all after split, %s[1|@] means separated by @ and specifies the second item. Supports replace, for example %s[].replace(/(\\d)/,"a$1"). Will read keywords from clipboard if there is no one',
                  param_p1: 'Post body, like %p{x=1&y=%s}',
                  param_p2: 'Post without navigation',
                  param_p3: 'Post in page by selector or xpath, like #p{#input=%u&sleep(500)&click(.submit)}, means: input current url to "#input", then wait for 500ms, then click ".submit". use \\& \\= instead of & = in content. wait(#input) means wait for element #input appeared, wait(!.loading) means wait for element .loading disappeared, call(alert("Hello")) means eval code alert("Hello"), which support await. @ means activeElement while input',
                  param_input: 'Input something, like %input{love who?,you}.Use / to create a drop down menu, eg %input{Please select your cup size,A/B/C}. You can also add descriptions separately, for example %input{Please select your cup/rare/excellent/So big,A/B/C}',
                  param_group: 'Batch open by site name you\'ve created',
                  param_ele: 'Query element for innerText from selector or xpath, like %element{.mainTitle}, return selected elements if selector is not set',
                  param_elep: 'Return prop value for queried element, like %element{.mainTitle}.prop(href) %element{.mainTitle}.prop(innerHTML)',
                  param_elere: 'Replace, same as above, like %element{.mainTitle}.prop(href).replace(/https/i,"")',
                  param_cp: 'Put this at first then all words after will be copied to the clipboard',
                  param_showTips: 'Display the acquired html code in the tips immediately when the mouse hovers, if an array is returned, the second item means the content will be copied after click, if the second item is a link, it will open after click. you can use fetch with cross-domain, and use storage.getItem/storage.setItem to operate persistent data, "name" is the name of current engine. It is also possible to use the simplified mode and pass in the link directly with the template, for example: showTips:https://api.xxx.xxx/xxx <i>{json.result|*%s} USD = %s RMB</i>，it means grabbing data from api.xxx.xxx, parsing it in json format, and putting the json.result into the <i> template and returning the tips. Another example: showTips:https://xxx.com/%sr <span>{title}</span><p>{.genre a|<mark>()</mark>}</p><img src="https://xxx.com{a.bigImage>img|src}"/> which means grabbing data from xxx.com, get the page title, iterate through the contents of all .genre a elements and create mark elements separately, get the src of a.bigImage>img image and create img elements',
                  param_find: 'Find in page and highlight, such as find:%s',
                  param_findadd: 'Add the target keyword to the highlighted preset group, for example, find.addto(reddit):%t.replace(/.*user/,"") means to extract the parameters after the "user" in the specified link and add into "@reddit" group',
                  javascript: 'Execute js code, window.keywords represents keywords, window.targetElement represents the pointing element. If the current page cannot execute the inline code, you can create a new GreaseMonkey script and paste the code, export the method to window, and call it through the method name. For example javascript:searchJumper_Function1',
                  param_date1: 'Current timestamp(ms)',
                  param_date2: 'Perform simple calculations on the current timestamp, such as %date{/1000 +604800}, which represents a timestamp calculated in seconds after one week',
                  aboutContent: "I use the search engine jump function very frequently in my work, but I found that most of them contain trojans after tried many related extensions. \nThis is just a simple function, so why not write one by myself? \nThe result is that writing the configuration page takes several times more energy than the script itself... 🤦‍\nThis search engine jump supports dragging and dropping with defined location, and also supports in-site search, word-marking search, and configuration import and export."
              }
              break;
      }
}
window.i18n = (name, param) => {
      return config[name]?config[name].replace("#t#",param):name;
}
window.setLang(lang);

setTimeout(() => {
      if (!window.searchData) window.location.reload();
}, 5000);

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

reportWebVitals();
