import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const lang = navigator.appName === 'Netscape' ? navigator.language : navigator.userLanguage;
let config = {};
switch (lang) {
    case 'zh-CN':
    case 'zh-SG':
        config = {
            name: '搜索酱',
            description: '详细描述',
            rulesStore: '站点规则仓库',
            import: '导入配置',
            export: '导出配置',
            general: '常规设置',
            searchEngines: '搜索引擎',
            exportConfig: '导出设置',
            findInPage: '页内查找',
            about: '关于',
            showInSearchEngine: '高亮搜索引擎页面',
            showInSearchEngineTips: '在搜索引擎结果页高亮关键词',
            showInSearchJumpPage: '高亮搜索引擎页面打开的站点',
            showInSearchJumpPageTips: '在搜索引擎页面点击打开的站点内高亮关键词',
            limitInPageLen: '限制关键词最小长度',
            limitInPageLenTips: '不对长度小于此值的关键词进行高亮',
            ignoreWords: '忽略关键词列表',
            inPageWordsStyles: '关键词样式',
            inPageWordsAddStyles: '自定义关键词CSS，数组内按顺序指向对应关键词',
            defaultPicker: '自动开启元素选择',
            defaultPickerTips: '打开搜索输入框时自动开启元素选择',
            altToHighlight: 'Alt 划选立即高亮',
            altToHighlightTips: '使用页内搜索功能时使用 Alt 划选后立即高亮',
            disableInputOnWords: '划选文字时不弹出搜索输入框',
            disableInputOnWordsTips: '在划选文字时使用快捷键不弹出搜索输入框',
            inPageRule: '站点自动高亮规则',
            errorNoType: '请输入类别名',
            errorSameType: '类别名不能重复',
            editType: '编辑类别',
            typeName: '类别名',
            typeIcon: '类别图标',
            category: '类别',
            iconTips: '图标可使用 FontAwsome、图片链接或者 base64 代码',
            typeMatch: '匹配 URL，设为 0 隐藏该类',
            typeEnableSelTxt: '对选择文字生效',
            typeEnableSelImg: '对图片生效',
            typeEnableSelAudio: '对音频生效',
            typeEnableSelVideo: '对视频生效',
            typeEnableSelLink: '对链接生效',
            typeEnableSelPage: '对页面生效',
            typeOpenInNewTab: '启用后该组链接将默认在新窗口打开',
            openSelect: '打开选项',
            openInNewTabOption: '新标签页打开',
            openInCurrentOption: '当前页打开',
            openInDefaultOption: '默认',
            showCurrent: '显示当前站点',
            showCurrentTips: '匹配到当前站点时，不隐藏当前站点图标',
            delete: '删除',
            cancel: '取消',
            edit: '编辑',
            editSite: '编辑站点',
            siteName: '站点名',
            siteUrl: '站点 URL',
            siteIcon: '站点图标',
            siteKeywords: '搜索词正则',
            siteMatch: '匹配 URL，设为 0 隐藏该站',
            siteCharset: '站点编码',
            toolbarPosition: '工具栏位置',
            portrait: '纵向',
            horizontal: '横向',
            openInNewTab: '默认在新标签页打开链接',
            openInNewTabTips: '启用后链接将全部默认在新标签页打开',
            enableInPage: '启用划词搜索',
            enableInPageTips: '启用后选择文字并长按鼠标右键可调出工具栏',
            bindFunctionKey: '绑定工具栏唤出配合功能键',
            ctrlKey: 'Ctrl键',
            altKey: 'Alt键',
            shiftKey: 'Shift键',
            metaKey: 'meta键',
            configContent: '设置源码',
            copy: '复制',
            save: '保存',
            autoClose: '自动合上类别',
            autoDelay: '隐藏延时',
            needName: '需要名称',
            needUrl: '需要 URL',
            overOpen: '鼠标划过类别自动展开',
            overOpenTips: '选中此项则当鼠标划过类别图标，对应类别将自动展开',
            selectToShow: '划选立即调用',
            selectToShowTips: '启用后无需长按鼠标，划选立即调出工具栏',
            autoCloseTips: '启用之后一旦鼠标离开搜索条，已打开的类别抽屉将会自动合上',
            enableShortcut: '启用站点快捷键',
            enableShortcutTips: '启用后，将使得所有为站点分配的快捷键生效',
            siteShotcut: '搜索快捷键',
            initShow: '打开页面立即拉开工具栏，鼠标划过后再贴边隐藏',
            presetCss: '预置样式',
            presetCssTips: '选择后载入预置样式',
            customCss: '自定义样式',
            replaceCss: '确定要替换当前编辑的样式吗？',
            enableInInput: '监听输入框',
            enableInInputTips: '启用后，在输入框内不忽略快捷键',
            fontAwesomeCss: 'FontAwesome CDN地址',
            nobatch: '不参与右键点击类别图标时的批量打开',
            hideNotMatch: '如果网址不匹配则隐藏该项',
            typeMatchTips: '仅在匹配站点显示该类别',
            siteUrlTips: '%s 查询词; %t 指向链接; %n 指向文字; %u 页面地址; %h 页面域名',
            customSize: '缩放工具栏',
            typeOpenTime: '类别展开耗时',
            longPressTime: '长按时间',
            typeShotcut: '批量打开快捷键',
            enableLeftMouse: '启用鼠标左键长按',
            enableLeftMouseTips: '启用后，鼠标左键长按也能触发。否则仅对鼠标右键生效',
            cacheSwitch: '缓存图标',
            sameSiteName: '在【#t#】下存在同名站点',
            sameShortcut: '【#t#】已经绑定了相同快捷键',
            noIcons: '纯文本模式',
            noIconsTips: '隐藏图标，仅显示纯文本',
            noAni: '禁止动画效果',
            noAniTips: '禁止所有动画效果',
            quickAddRule: '快速添加搜索引擎',
            quickAddRuleTips: '按住 Ctrl + Shift 点击任意搜索框快速添加搜索引擎',
            searchMycroft: '💎 在 mycroftproject 上搜索其他人编辑好的搜索引擎并一键导入，例如：“谷歌学术”',
            showSiteLists: '显示下拉列表',
            showSiteListsTips: '启用后将在类别图标旁启用下拉列表',
            alwaysShowSiteLists: '总是显示下拉列表',
            alwaysShowSiteListsTips: '启用后，类别抽屉打开时也会显示下拉列表',
            historyLength: '历史站点数',
            historyLengthTips: '在默认展开的类别中插入数个最近访问的站点',
            sortType: '自动排序类别',
            sortTypeTips: '自动按照访问次数重新排序类别',
            multiline: '多行搜索，选取多行文字时，以换行符分隔，按行搜索',
            multilineLabel: '开关',
            multilineGap: '搜索间隔',
            disable: '禁用',
            enable: '启用',
            ask: '询问',
            batchAction: '批量操作',
            selectAll: '全选',
            invert: '反选',
            deleteConfirm: '你确定要删除这些站点吗？',
            moveTo: '移动至',
            moveToConfirm: '你确定要将这些站点移动至【#t#】吗?',
            autoHide: '自动隐藏搜索条',
            autoHideTips: '达到上方设置延时之后，自动隐藏搜索条',
            autoHideAll: '完全隐藏',
            autoHideAllTips: '隐藏时使得搜索条完全消失',
            dragToSearch: '开启拖拽搜索',
            dragToSearchTips: '开启后拖拽文字、链接或者图片进行搜索，内圈为当前分类前6个站点，外圈为最近使用的站点',
            sameSiteUrl: '站点Url不能重复',
            clone: '克隆',
            cloneConfirm: '你确定要将这些站点克隆至 【#t#】?',
            cloneAction: '你想要将它们克隆成一个集合吗?',
            groupName: '集合名',
            donate: '💞如果对你有帮助，请通过以下方式打赏，以勉励我继续维护',
            importBookmarks: '导入浏览器书签',
            jsonToolong: '站点数据过于庞大，是否继续格式化为JSON文本？',
            cacheSwitchTips: '浏览网页时在后台缓存图标为 base64 图片至配置，以免 icon 请求拉低性能，注意开启后会弹出跨域请求',
            searchFontawesome: '🚩 搜索 FontAwesome 图标用于类别项',
            keywordRegTips: '单个关键词：wd；多个关键词：wd|qw|key；正则分组：(?:word)=(.*?)(&|$)',
            localAppAddBtn: '添加自定义本地应用调用',
            localApp: '本地应用调用',
            localAppCall: '调用命令',
            localAppName: '自定义调用头，可留空，编辑前注意备份注册表',
            localAppUnknowCall: '无法分析此命令，请检查命令或者手动构造注册表',
            localAppWrongName: '调用头只能输入数字或者字母',
            callInputKey: '唤出搜索输入框的快捷键',
            defaultFindTab: '默认显示页内查找',
            defaultFindTabTips: '打开搜索输入框时默认显示页内查找，否则默认显示站点筛选',
            geneRegFile: '生成注册表补丁',
            targetTxt: '划词搜索分类',
            targetImg: '以图搜图分类',
            targetLink: '链接处理分类',
            targetPage: '当前页面分类',
            hideDragHistory: '隐藏拖拽轮盘外圈',
            hideDragHistoryTips: '隐藏拖拽轮盘中用于存放最近 10 个历史访问站点的外圈',
            aboutContent: '平时工作中搜索引擎跳转功能用得很频繁，但尝试了相关的扩展，发现大多夹有私货。\n\n而这只是一个简单功能，所以不如自己写一个啦。\n\n结果写配置页面耗费的精力数倍于脚本本身……🤦‍\n\n这个搜索引擎跳转支持自己拖拽定义位置，同时也支持站内搜索，多语言编码设置（例如shift-jis），划词搜索，以及配置导入导出。'
        }
        break;
    case 'zh-TW':
    case 'zh-HK':
        config = {
            name: '搜索醬',
            description: '詳細描述',
            rulesStore: '站點規則倉庫',
            import: '導入配置',
            export: '導出配置',
            general: '常規設置',
            searchEngines: '搜尋引擎',
            exportConfig: '導出設置',
            findInPage: '頁内查找',
            about: '關於',
            showInSearchEngine: '高亮搜尋引擎頁面',
            showInSearchEngineTips: '在搜尋引擎結果頁高亮關鍵詞',
            showInSearchJumpPage: '高亮搜尋引擎頁面開啟的站點',
            showInSearchJumpPageTips: '在搜尋引擎頁面點選開啟的站點內高亮關鍵詞',
            limitInPageLen: '限制關鍵詞最小長度',
            limitInPageLenTips: '不對長度小於此值的關鍵詞進行高亮',
            ignoreWords: '忽略關鍵詞列表',
            inPageWordsStyles: '關鍵詞樣式',
            inPageWordsAddStyles: '自定義關鍵詞CSS，數組内按順序指向對應關鍵詞',
            defaultPicker: '自動開啟元素選擇',
            defaultPickerTips: '打開搜索輸入框時自動開啟元素選擇',
            altToHighlight: 'Alt 劃選立即高亮',
            altToHighlightTips: '使用頁內搜索功能時使用 Alt 劃選後立即高亮',
            disableInputOnWords: '劃選文字時不彈出搜索輸入框',
            disableInputOnWordsTips: '在劃選文字時使用快捷鍵不彈出搜索輸入框',
            inPageRule: '站點自動高亮規則',
            errorNoType: '請輸入類別名',
            errorSameType: '類別名不能重複',
            editType: '編輯類別',
            typeName: '類別名',
            typeIcon: '類別圖標',
            category: '類別',
            iconTips: '圖標可使用 FontAwsome、圖片連結或者 base64 代碼',
            typeMatch: '匹配 URL，設爲 0 隱藏該類',
            typeEnableSelTxt: '對選擇文字生效',
            typeEnableSelImg: '對圖片生效',
            typeEnableSelAudio: '對音頻生效',
            typeEnableSelVideo: '對視頻生效',
            typeEnableSelLink: '對鏈接生效',
            typeEnableSelPage: '對頁面生效',
            typeOpenInNewTab: '啟用後該組連結將默認在新窗口打開',
            openSelect: '打開選項',
            openInNewTabOption: '新標簽頁打開',
            openInCurrentOption: '當前頁打開',
            openInDefaultOption: '默認打開選項',
            showCurrent: '顯示當前站點',
            showCurrentTips: '匹配到當前站點時，不隱藏當前站點圖標',
            delete: '刪除',
            cancel: '取消',
            edit: '編輯',
            editSite: '編輯站點',
            siteName: '站點名',
            siteUrl: '站點 URL',
            siteIcon: '站點圖標',
            siteKeywords: '搜索詞正則',
            siteMatch: '匹配 URL，設爲 0 隱藏該站',
            siteCharset: '站點編碼',
            toolbarPosition: '工具欄位置',
            portrait: '縱向',
            horizontal: '橫向',
            openInNewTab: '默認在新標籤頁打開連結',
            openInNewTabTips: '啟用後連結將全部默認在新標籤頁打開',
            enableInPage: '啟用劃詞搜索',
            enableInPageTips: '啟用後選擇文字並長按滑鼠右鍵可調出工具欄',
            bindFunctionKey: '綁定工具欄喚出配合功能鍵',
            ctrlKey: 'Ctrl鍵',
            altKey: 'Alt鍵',
            shiftKey: 'Shift鍵',
            metaKey: 'meta鍵',
            configContent: '設置源碼',
            copy: '複製',
            save: '保存',
            autoClose: '自動合上類別',
            autoDelay: '隱藏延時',
            needName: '需要名稱',
            needUrl: '需要 URL',
            overOpen: '滑鼠划過類別自動展開',
            overOpenTips: '選中此項則當滑鼠划過類別圖標，對應類別將自動展開',
            selectToShow: '劃選立即調用',
            selectToShowTips: '啟用後無需長按滑鼠，劃選立即調出工具欄',
            autoCloseTips: '啟用之後一旦滑鼠離開搜索條，已打開的類別抽屜將會自動合上',
            enableShortcut: '啟用站點快捷鍵',
            enableShortcutTips: '啟用後，將使得所有為站點分配的快捷鍵生效',
            siteShotcut: '搜索快捷鍵',
            initShow: '打開頁面立即拉開工具欄，鼠標划過后再貼邊隱藏',
            presetCss: '預置樣式',
            presetCssTips: '選擇后載入預置樣式',
            customCss: '自定義樣式',
            replaceCss: '確定要替換當前編輯的樣式嗎？',
            enableInInput: '監聽輸入框',
            enableInInputTips: '啓用後，在輸入框内不忽略快捷鍵',
            fontAwesomeCss: 'FontAwesome CDN地址',
            nobatch: '不參與右鍵點擊類別圖標時的批量打開',
            hideNotMatch: '如果網址不匹配則隱藏該項',
            typeMatchTips: '僅在匹配站點顯示該類別',
            siteUrlTips: '%s 查詢詞; %t 指向連結; %n 指向文字; %u 頁面地址; %h 頁面域名',
            customSize: '縮放工具欄',
            typeOpenTime: '類別展開耗時',
            longPressTime: '長按時間',
            typeShotcut: '批量打開快捷鍵',
            enableLeftMouse: '啟用滑鼠左鍵長按',
            enableLeftMouseTips: '啟用後，滑鼠左鍵長按也能觸發。否則僅對滑鼠右鍵生效',
            cacheSwitch: '緩存圖標',
            sameSiteName: '在【#t#】下存在同名站點',
            sameShortcut: '【#t#】已經綁定了相同快捷鍵',
            noIcons: '純文本模式',
            noIconsTips: '隱藏圖標，僅顯示純文本',
            noAni: '禁止動畫效果',
            noAniTips: '禁止所有動畫效果',
            quickAddRule: '快速添加搜尋引擎',
            quickAddRuleTips: '按住 Ctrl + Shift 點擊任意搜索框快速添加搜尋引擎',
            searchMycroft: '💎 在 mycroftproject 上搜索其他人編輯好的搜尋引擎並一鍵導入',
            showSiteLists: '顯示下拉列表',
            showSiteListsTips: '啓用後將在類別圖標旁啓用下拉列表',
            alwaysShowSiteLists: '總是顯示下拉列表',
            alwaysShowSiteListsTips: '啟用後，類別抽屜打開時也會顯示下拉列表',
            historyLength: '歷史站點數',
            historyLengthTips: '在默認展開的類別中插入數個最近訪問的站點',
            sortType: '自動排序類別',
            sortTypeTips: '自動按照訪問次數重新排序類別',
            multiline: '多行搜索，選取多行文字時，以換行符分隔，按行搜索',
            multilineLabel: '開關',
            multilineGap: '搜索間隔',
            disable: '禁用',
            enable: '啟用',
            ask: '詢問',
            batchAction: '批量操作',
            selectAll: '全選',
            invert: '反選',
            deleteConfirm: '你確定要刪除這些站點嗎？',
            moveTo: '移動至',
            moveToConfirm: '你確定要將這些站點移動至【#t#】嗎?',
            autoHide: '自動隱藏搜索條',
            autoHideTips: '達到上方設置延時之後，自動隱藏搜索條',
            autoHideAll: '完全隱藏',
            autoHideAllTips: '隱藏時使得搜索條完全消失',
            dragToSearch: '開啟拖拽搜索',
            dragToSearchTips: '開啟後拖拽文字、連結或者圖片進行搜索，內圈為當前分類前6個站點，外圈為最近使用的站點',
            sameSiteUrl: '站點Url不能重複',
            clone: '克隆',
            cloneConfirm: '你確定要將這些站點克隆至 【#t#】?',
            cloneAction: '你想要將它們克隆成一個集合嗎?',
            groupName: '集合名',
            donate: '💞如果對你有幫助，請通過以下方式打賞，以勉勵我繼續維護',
            importBookmarks: '導入瀏覽器書簽',
            jsonToolong: '站點數據過於龐大，是否繼續格式化為JSON文本？',
            cacheSwitchTips: '瀏覽網頁時在後台緩存圖標為base64圖片，注意開啟後會彈出跨域請求',
            searchFontawesome: '🚩 搜索 FontAwesome 圖標用於類別項',
            keywordRegTips: '單個關鍵詞：wd；多個關鍵詞：wd|qw|key；正則分組：(?:word)=(.*?)(&|$)',
            localAppAddBtn: '添加自定義本地應用調用',
            localApp: '本地應用調用',
            localAppCall: '調用命令',
            localAppName: '自定義調用頭，可留空，編輯前注意備份注冊表',
            localAppUnknowCall: '無法分析此命令，請檢查命令或者手動構造註冊表',
            localAppWrongName: '調用頭只能輸入數字或者字母',
            callInputKey: '喚出搜索輸入框的快捷鍵',
            defaultFindTab: '默認顯示頁內查找',
            defaultFindTabTips: '打開搜索輸入框時默認顯示頁內查找，否則默認顯示站點篩選',
            geneRegFile: '生成註冊表補丁',
            targetTxt: '劃詞搜索分類',
            targetImg: '以圖搜圖分類',
            targetLink: '鏈接處理分類',
            targetPage: '當前頁面分類',
            hideDragHistory: '隱藏拖拽輪盤外圈',
            hideDragHistoryTips: '隱藏拖拽輪盤中用於存放最近 10 個歷史訪問站點的外圈',
            aboutContent: '平時工作中搜尋引擎跳轉功能用得很頻繁，但嘗試了相關的擴展，發現大多夾有私貨。\n\n而這只是一個簡單功能，所以不如自己寫一個啦。\n\n結果寫配置頁面耗費的精力數倍於腳本本身……🤦‍\n\n這個搜尋引擎跳轉支持自己拖拽定義位置，同時也支持站內搜索，多語言編碼設置（例如shift-jis），劃詞搜索，以及配置導入導出。'
        }
        break;
    default:
        config = {
            name: 'SearchJumper',
            description: 'Description',
            rulesStore: 'Search Engine Collection Store',
            import: 'Import config',
            export: 'Export JSON',
            general: 'General',
            searchEngines: 'Search Engines',
            exportConfig: 'Export Config',
            findInPage: 'Find In Page',
            about: 'About',
            showInSearchEngine: 'Highlight search engine page',
            showInSearchEngineTips: 'Highlight keywords on the search engine results page',
            showInSearchJumpPage: 'Highlight the site opened from the search engine',
            showInSearchJumpPageTips: 'Highlight keywords on the page opened by click on the search engine',
            limitInPageLen: 'Limit the minimum length of keywords',
            limitInPageLenTips: 'Do not highlight keywords whose length is less than this value',
            ignoreWords: 'Ignore keyword list',
            inPageWordsStyles: 'Keyword styles',
            inPageWordsAddStyles: 'Custom keyword CSS, input an array target each keyword',
            defaultPicker: 'Auto enable element selection',
            defaultPickerTips: 'Automatically enable element selection when opening the search input box',
            altToHighlight: 'Alt swipe to highlight immediately',
            altToHighlightTips: 'When using the in-page search function, use Alt to highlight immediately after selection',
            disableInputOnWords: 'No search input when selecting text',
            disableInputOnWordsTips: 'Do not pop up the search input when swiping text with shortcut key',
            inPageRule: 'Site auto-highlighting rules',
            errorNoType: 'Please enter the category name',
            errorSameType: 'Found same category name',
            editType: 'Edit category',
            typeName: 'Category name',
            typeIcon: 'Category icon',
            category: 'Category',
            iconTips: 'The icon can use FontAwsome, image link or base64 code',
            typeMatch: 'Match url, hide by set to 0',
            typeEnableSelTxt: 'Effect on text',
            typeEnableSelImg: 'Effect on image',
            typeEnableSelAudio: 'Effect on audio',
            typeEnableSelVideo: 'Effect on video',
            typeEnableSelLink: 'Effect on link',
            typeEnableSelPage: 'Effect on page',
            typeOpenInNewTab: 'After enabling, this group of links will be opened in a new window by default',
            openSelect: 'Open mode',
            openInNewTabOption: 'Open in new tab',
            openInCurrentOption: 'Open in current',
            openInDefaultOption: 'Open by default',
            showCurrent: 'Show current site',
            showCurrentTips: 'Show the site button of current when matched',
            delete: 'Delete',
            cancel: 'Cancel',
            edit: 'Edit',
            editSite: 'Edit site',
            siteName: 'Site name',
            siteUrl: 'Site URL',
            siteIcon: 'Site icon',
            siteKeywords: 'RegExp of search keywords',
            siteMatch: 'RegExp of match url, hide by set to 0',
            siteCharset: 'Charset',
            toolbarPosition: 'Toolbar position',
            portrait: 'Portrait',
            horizontal: 'Horizontal',
            openInNewTab: 'Open links in new tabs by default',
            openInNewTabTips: 'When enabled, the link will be opened in a new tab by default',
            enableInPage: 'Enable select to search',
            enableInPageTips: 'After enabling, select some text and long press the right mouse to bring up the toolbar',
            bindFunctionKey: 'Bind function key for mouse to call out toolbar',
            ctrlKey: 'Ctrl key',
            altKey: 'Alt key',
            shiftKey: 'Shift key',
            metaKey: 'Meta key',
            configContent: 'Config source code',
            copy: 'Copy',
            save: 'Save',
            autoClose: 'Auto close type',
            autoDelay: 'Hide delay',
            needName: 'Require name',
            needUrl: 'Require url',
            overOpen: 'Mouse over to expand category automatically ',
            overOpenTips: 'If you select this item, when the mouse moves over the category icon, the corresponding category will be automatically expanded',
            selectToShow: 'Select to call',
            selectToShowTips: 'After enabling, no need to long-press mouse, select to bring up the toolbar immediately',
            autoCloseTips: 'When enabled, opened category drawer will be closed automatically once the mouse leaves the search bar',
            enableShortcut: 'Enable site shortcuts',
            enableShortcutTips: 'After enabling, all shortcut keys assigned to single site will take effect',
            siteShotcut: 'Search shortcut key',
            initShow: 'Pull out to show when page initializes',
            presetCss: 'Preset Css',
            presetCssTips: 'Select to load preset css',
            customCss: 'Custom Css',
            replaceCss: 'Do you confirm to replace current css?',
            enableInInput: 'Enable on input',
            enableInInputTips: 'Enable shortcut on input or textarea',
            fontAwesomeCss: 'FontAwesome CDN URL',
            nobatch: 'Do not participate in batch open when right-clicking category icon',
            hideNotMatch: 'Hide icon if don\'t macth',
            typeMatchTips: 'Show this category only when url matches',
            siteUrlTips: '%s keywords; %t target URL; %n target content; %u site URL; %h hostname',
            customSize: 'Zoom toolbar',
            typeOpenTime: 'Category expansion time',
            longPressTime: 'Long press time',
            typeShotcut: 'Shortcut for batch open',
            enableLeftMouse: 'Also effect with left mouse',
            enableLeftMouseTips: 'Also effect after long press the left mouse button, otherwise only effect with right mouse button',
            cacheSwitch: 'Cache icons',
            sameSiteName: 'Site under 【#t#】 has the same name',
            sameShortcut: '【#t#】 has already bind the same shortcut',
            noIcons: 'Plain text mode',
            noIconsTips: 'Show only plain text without any icon',
            noAni: 'Disable animation effects',
            noAniTips: 'Disable all animation effects',
            quickAddRule: 'Quick Add Site',
            quickAddRuleTips: 'Click any search input box with Ctrl + Shift to add site quickly',
            searchMycroft: '💎 Search site config on mycroftproject for import by one click',
            showSiteLists: 'Show drop-down list',
            showSiteListsTips: 'After enabled, the drop-down list will be enabled next to the category icon',
            alwaysShowSiteLists: 'Always show drop-down lists',
            alwaysShowSiteListsTips: 'After enabled, the drop-down list will be enabled even when category opened',
            historyLength: 'Number of historical sites',
            historyLengthTips: 'Insert several recently visited sites in the default expanded category',
            sortType: 'Auto sort categories',
            sortTypeTips: 'Automatically reorder categories according to the number of visits',
            multiline: 'Multi-line text search, separated by line feed, search by single line',
            multilineLabel: 'Switch',
            multilineGap: 'Search Gap',
            disable: 'Disable',
            enable: 'Enable',
            ask: 'Ask',
            batchAction: 'Batch Action',
            selectAll: 'Select All',
            invert: 'Invert',
            deleteConfirm: 'Do you want to delete these sites?',
            moveTo: 'Move to',
            moveToConfirm: 'Do you want to move these sites to 【#t#】?',
            autoHide: 'Auto hide bar',
            autoHideTips: 'Auto hide search bar after hide delay set before',
            autoHideAll: 'Completely hide',
            autoHideAllTips: 'Hide the search bar for completely disappear',
            dragToSearch: 'Enable drag to search',
            dragToSearchTips: 'Drag text, link or image to search quickly, the inner circle contains the top 6 sites in the current category, and the outer circle contains the most recently used sites',
            sameSiteUrl: 'Found a site with same url',
            clone: 'Clone',
            cloneConfirm: 'Do you want to clone these sites to 【#t#】?',
            cloneAction: 'Do you want to clone as one group instead of a single site?',
            groupName: 'Group Name',
            donate: '💞Buy me a coffee if it helps you',
            importBookmarks: 'Import browser bookmarks',
            jsonToolong: 'The sites data is too long, do you want to continue format to json?',
            cacheSwitchTips: 'The icons will cached with base64 images in the background when browsing, but some cross-domain requests will pop up',
            searchFontawesome: '🚩 Search icons for category from FontAwesome.com',
            keywordRegTips: 'Single: wd, Multiple: wd|qw|key, RegExp group: (?:word)=(.*?)(&|$)',
            localAppAddBtn: 'Call local application',
            localApp: 'Local application call',
            localAppCall: 'Call command',
            localAppName: 'Custom call header, can be left blank',
            localAppUnknowCall: 'Unable to parse this command, please check the command or manually construct the registry',
            localAppWrongName: 'The call header can only enter with numbers or letters',
            callInputKey: 'Shortcut key for calling out the search input',
            defaultFindTab: 'Default to display find in page',
            defaultFindTabTips: 'When the search input is opened, the find-in-page will be displayed by default, otherwise the site filter will be displayed by default',
            geneRegFile: 'Generate registry patch',
            targetTxt: 'Words search',
            targetImg: 'Image search',
            targetLink: 'Link Search',
            targetPage: 'Current page',
            hideDragHistory: 'Hide the outer ring of the drag wheel',
            hideDragHistoryTips: 'Hide the outer ring of the drag wheel which storing the last 10 historically visited sites',
            aboutContent: "I use the search engine jump function very frequently in my work, but I found that most of them contain trojans after tried many related extensions. \n\nThis is just a simple function, so why not write one by myself? \n\nThe result is that writing the configuration page takes several times more energy than the script itself... 🤦‍\n\nThis search engine jump supports dragging and dropping with defined location, and also supports in-site search, word-marking search, and configuration import and export."
        }
        break;
}
window.i18n = (name, param) => {
    return config[name]?config[name].replace("#t#",param):name;
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

reportWebVitals();
